language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: a768d357d5cf298ba29138fe3852b8a26b5ed607ee34011f9df8b343bf7e93cc
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
